DROP TABLE MATCH_DETAILS cascade constraints;
DROP TABLE BUYER_DETAILS cascade constraints;
DROP TABLE TICKET_INFO cascade constraints;

CREATE TABLE MATCH_DETAILS(
	MATCH_NO NUMBER(2) NOT NULL,
	MATCH_VANUE VARCHAR(9),
	MATCH_TIME DATE,
	MATCH_TYP VARCHAR(10),
	TEAM_NAME1 VARCHAR(4),
	TEAM_NAME2 VARCHAR(4),
	TOTAL_SEAT NUMBER(10)
);


CREATE TABLE BUYER_DETAILS(
	BUYER_ID VARCHAR(8) NOT NULL,
	TICKET_ID VARCHAR(9),
	TOTAL_PRICE NUMBER(10),
	TICKET_CATEGORY NUMBER(1) check(TICKET_CATEGORY >= 1 and TICKET_CATEGORY <= 4),
	NO_OF_SEAT_NEEDED NUMBER(10) check(NO_OF_SEAT_NEEDED >= 1 and NO_OF_SEAT_NEEDED <= 4)
);

CREATE TABLE TICKET_INFO(
	TICKET_ID VARCHAR(9) NOT NULL,
	SEAT_NO VARCHAR(6),
	SEAT_TYP VARCHAR(8),
	MATCH_NO NUMBER(2)
);

-------------------------------------- PRIMARY KEY ----------------------------------------------
ALTER TABLE MATCH_DETAILS ADD CONSTRAINT MDP_KEY PRIMARY KEY(MATCH_NO);
ALTER TABLE BUYER_DETAILS ADD CONSTRAINT BDP_KEY PRIMARY KEY(BUYER_ID);
ALTER TABLE TICKET_INFO ADD CONSTRAINT TIP_KEY PRIMARY KEY(TICKET_ID);

-------------------------------------- FOREIGN KEY ----------------------------------------------
ALTER TABLE TICKET_INFO ADD CONSTRAINT TIF_KEY FOREIGN KEY (MATCH_NO) REFERENCES MATCH_DETAILS(MATCH_NO) on delete cascade;
ALTER TABLE BUYER_DETAILS ADD CONSTRAINT BDF_KEY FOREIGN KEY (TICKET_ID) REFERENCES TICKET_INFO(TICKET_ID) on delete cascade;



INSERT INTO MATCH_DETAILS VALUES(1,'DHA','01-JAN-2017','GROUP','BAN','IND',10000);
INSERT INTO MATCH_DETAILS VALUES(2,'CHI','02-JAN-2017','GROUP','AUS','SAF',20000);
INSERT INTO MATCH_DETAILS VALUES(3,'KHU','03-JAN-2017','SUPER','NZ','PK',30000);
INSERT INTO MATCH_DETAILS VALUES(4,'DHA','05-JAN-2017','SUPER','SL','WI',40000);
INSERT INTO MATCH_DETAILS VALUES(5,'KHU','06-JAN-2017','SEMIFINAL','END','ZIM',50000);


INSERT INTO TICKET_INFO VALUES('A1001','N-01','NORMAL',1);
INSERT INTO TICKET_INFO VALUES('B2001','N-02','NORMAL',2);
INSERT INTO TICKET_INFO VALUES('B2002','M-01','MIDDLE',2);
INSERT INTO TICKET_INFO VALUES('A3002','N-02','MIDDLE',3);
INSERT INTO TICKET_INFO VALUES('A3001','M-01','VIP',3);
INSERT INTO TICKET_INFO VALUES('A3003','M-02','VIP',2);

COMMIT;